CREATE TABLE IF NOT EXISTS users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	email varchar(512) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	description varchar(1024) NOT NULL,
	available bool NOT NULL DEFAULT true,
	owner_id bigint NOT NULL,
	item_request_id bigint NULL,
	CONSTRAINT pk_item PRIMARY KEY (id),
	CONSTRAINT fk_owner_item FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE
);